**Part 3: Policy RAG | Step 5: Faithfulness and abstention**  
Goal: check that answers are supported by the cited clauses, and that unanswerable questions get "not found".

In [1]:
import sys, json
from pathlib import Path
import pandas as pd

# Find the project root: the folder that contains src/policy_rag.py
ROOT = next(p for p in [Path.cwd(), *Path.cwd().parents] if (p / "src" / "policy_rag.py").exists())
sys.path.append(str(ROOT / "src"))
import policy_rag as rag

POLICY_DIR = ROOT / "notebooks" / "RAG" / "policy"
OUT_DIR = ROOT / "notebooks" / "RAG" / "outputs"
OUT_DIR.mkdir(exist_ok=True)
pd.set_option("display.max_colwidth", 70)
pd.set_option("display.width", 200)

**Step. Load the saved answers and the correct labels.**

In [2]:
results = json.loads((OUT_DIR / "answers.json").read_text(encoding="utf-8"))
eval_df = pd.read_csv(POLICY_DIR / "eval_questions.csv")
chunks = rag.chunk_policy(rag.load_policy(POLICY_DIR / "marketplace_policy.txt"))
index = rag.PolicyIndex(chunks)
len(results)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

20

**Step. Abstention and citation summary.** How the 4 unanswerable and 16 answerable questions were handled.

In [3]:
print(rag.summarize_answers(results).to_string())
print()
df = pd.DataFrame(results)
df[df["gold_answerable"] != df["answerable"].astype(int)][["qid", "gold_answerable", "answerable", "abstained_by", "answer"]]

unanswerable abstained (correct)       4 of 4
answerable wrongly abstained          1 of 16
answerable cited a correct clause    16 of 16

   qid  gold_answerable  answerable abstained_by                                                                 answer
6  Q07                1       False          llm  The provided clauses do not define the delay classes (Minor, Moder...

**Inference**
- All 4 unanswerable questions (Q17 to Q20) were refused, so the "not found" rule worked on every near-miss question.
- 1 of 16 answerable questions was refused wrongly: Q07. The refusal came from the LLM (`abstained_by` = llm), not from the score threshold.
- The Q07 answer starts with "The provided clauses do not define the delay classes". The missing clause is `MOP-2.2`, the clause that defines the classes. This matches notebook 03, where the top 3 of hybrid search (`MOP-3.2`, `MOP-3.1`, `MOP-3.4`) did not contain it.
- The refusal is the correct behaviour for the context given: the model refused instead of guessing a delay class.
- "Cited a correct clause: 16 of 16" is a loose check. It counts Q07 too (refused, but it cited `MOP-3.2`), and it needs only one correct clause per question, not all of them.

**Step. The wrong answer in full.** The table above cuts long text after 70 characters. This prints the complete answer of every question where the result differs from the correct label.

In [4]:
wrong = [r for r in results if r["gold_answerable"] != int(r["answerable"])]
for r in wrong:
    print(r["qid"], "| abstained_by:", r["abstained_by"], "| retrieved:", ", ".join(r["retrieved_ids"]))
    print("  Q:", r["question"])
    print("  A:", r["answer"])
    print()

Q07 | abstained_by: llm | retrieved: MOP-3.2, MOP-3.1, MOP-3.4
  Q: An order worth R$ 500 is delivered 12 days late. How much platform credit does the customer get automatically?
  A: The provided clauses do not define the delay classes (Minor, Moderate, Severe, Critical), so a 12-day delay cannot be placed in a class. The credit therefore cannot be determined. MOP-3.2 gives the credit for each class. For a R$ 500 order, Minor is none, Moderate is the greater of R$ 20 or 10% (R$ 50), so R$ 50, and Severe is the greater of R$ 50 or 20% (R$ 100), so R$ 100. Critical is 100% of order value (R$ 500) plus freight, and the freight amount is not given. Under MOP-3.1 the compensation is issued as platform credit by default.

**Step. Faithfulness checks on answered questions.** Three checks: cited IDs are real, numbers in the answer come from the clauses or the question, and an LLM judge compares answer and clauses. This makes one LLM call per answered question.

In [5]:
checks = []
for r in results:
    c = rag.check_faithfulness(index, r)
    if c:
        checks.append({"qid": r["qid"], **c})
chk = pd.DataFrame(checks)
print(chk["verdict"].value_counts().to_string())
chk

verdict
SUPPORTED    14
PARTIAL       1

    qid  citations_valid ungrounded_numbers    verdict                                                                 reason
0   Q01             True                 []  SUPPORTED  Every step follows from the tier thresholds in 1.2 and the both-th...
1   Q02             True                 []  SUPPORTED  The answer restates the 15-order threshold and the Unrated classif...
2   Q03             True                 []  SUPPORTED  Clause 1.5 states that Gold sellers get a reduced commission rate ...
3   Q04             True                 []  SUPPORTED  Every claim matches the clauses: 7 days is Moderate with a freight...
4   Q05             True                [2]  SUPPORTED  Grace allowance of 4 days applies to Northeast non-Express orders,...
5   Q06             True                 []  SUPPORTED  The answer correctly applies 2.4 (no grace for Express), 2.2 (3 da...
6   Q08             True                 []  SUPPORTED  The answer correctly applies both thresholds to R$ 1,500 (Head app...
7   Q09             True                 []  SUPPORTED  Every claim in the answer matches clauses 3.1, 4.1 and 4.3: credit...
8   Q10             True                 []  SUPPORTED  Every claim matches the clauses: Pix refunds take 3 business days ...
9   Q11             True                 []  SUPPORTED  Every claim in the answer matches clauses 5.2 and 2.3: removal is ...
10  Q12             True                 []  SUPPORTED  The answer restates clause 5.4 accurately: requests must be raised...
11  Q13             True                 []  SUPPORTED  The answer restates clause 6.2 (restriction after remaining in Wat...
12  Q14             True                 []  SUPPORTED  The answer restates all four requirements from clause 6.4 accurate...
13  Q15             True                 []  SUPPORTED  Clauses 7.1 and 1.5 state that Gold sellers can use Rapid Payout (...
14  Q16             True                 []    PARTIAL  The customer-pays claim for change-of-mind returns matches clause ...

**Inference**
- 15 answers were checked: the 15 questions that were answered. Q07 and the 4 unanswerable questions have no answer to check.
- 14 of 15 are SUPPORTED and 1 is PARTIAL (Q16). No answer is UNSUPPORTED.
- `citations_valid` is True for all 15, so every cited ID was a clause that was retrieved.
- The Q16 reason is cut off in the table. The full text is printed in Step 3b.

**Step. Faithfulness checks in full.** Prints every verdict and reason without cutting the text, and saves them to `outputs/faithfulness.json`.

In [6]:
for _, row in chk.iterrows():
    print(f"{row['qid']} | {row['verdict']} | citations_valid={row['citations_valid']} | "
          f"ungrounded_numbers={row['ungrounded_numbers']}")
    print("  reason:", row["reason"])
    print()

chk.to_json(OUT_DIR / "faithfulness.json", orient="records", indent=2, force_ascii=False)

Q01 | SUPPORTED | citations_valid=True | ungrounded_numbers=[]
  reason: Every step follows from the tier thresholds in 1.2 and the both-thresholds rule and matching example in 1.3.

Q02 | SUPPORTED | citations_valid=True | ungrounded_numbers=[]
  reason: The answer restates the 15-order threshold and the Unrated classification for the trailing 90-day window, both of which are in the clause.

Q03 | SUPPORTED | citations_valid=True | ungrounded_numbers=[]
  reason: Clause 1.5 states that Gold sellers get a reduced commission rate of 11% against the standard 14%, which is exactly what the answer says.

Q04 | SUPPORTED | citations_valid=True | ungrounded_numbers=[]
  reason: Every claim matches the clauses: 7 days is Moderate with a freight chargeback, delay is measured against the checkout estimate, the waiver conditions and 10-day window apply, and no freight amount is stated. Omitting the 'or of the auto-cancellation date' option is not a contradiction, since auto-cancellation does not apply to a Moderate delay.

Q05 | SUPPORTED | citations_valid=True | ungrounded_numbers=['2']
  reason: Grace allowance of 4 days applies to Northeast non-Express orders, 6-4=2 days falls in the Minor 1–3 day class per clause 2.2.

Q06 | SUPPORTED | citations_valid=True | ungrounded_numbers=[]
  reason: The answer correctly applies 2.4 (no grace for Express), 2.2 (3 days is Minor), and 8.4 (Express delayed beyond 2 days is at least Moderate), with the freight chargeback consequence taken from the 2.2 table.

Q08 | SUPPORTED | citations_valid=True | ungrounded_numbers=[]
  reason: The answer correctly applies both thresholds to R$ 1,500 (Head approval plus Exceptions Register entry for >R$1,000, Quality lead approval for >R$300) and accurately notes the clause is silent on whether both approvals are needed cumulatively.

Q09 | SUPPORTED | citations_valid=True | ungrounded_numbers=[]
  reason: Every claim in the answer matches clauses 3.1, 4.1 and 4.3: credit is the default, cash refunds need one of four conditions, and partial remedies must use credit.

Q10 | SUPPORTED | citations_valid=True | ungrounded_numbers=[]
  reason: Every claim matches the clauses: Pix refunds take 3 business days (4.2), the 4.1 cases are listed correctly, platform credit is the default (3.1), and the clauses give no processing time for platform credit.

Q11 | SUPPORTED | citations_valid=True | ungrounded_numbers=[]
  reason: Every claim in the answer matches clauses 5.2 and 2.3: removal is barred on those grounds, waived-liability reviews are excluded from ARR but stay visible, and the waiver request must be made within 10 calendar days.

Q12 | SUPPORTED | citations_valid=True | ungrounded_numbers=[]
  reason: The answer restates clause 5.4 accurately: requests must be raised within 30 days of the review posting, the moderation decision is final, and there is no second-level appeal.

Q13 | SUPPORTED | citations_valid=True | ungrounded_numbers=[]
  reason: The answer restates clause 6.2 (restriction after remaining in Watch tier at the end of the 30-day period from 6.1), with only a trivial paraphrase of 'remain' as 'remain active'.

Q14 | SUPPORTED | citations_valid=True | ungrounded_numbers=[]
  reason: The answer restates all four requirements from clause 6.4 accurately, including the 6.3 exception, with nothing added.

Q15 | SUPPORTED | citations_valid=True | ungrounded_numbers=[]
  reason: Clauses 7.1 and 1.5 state that Gold sellers can use Rapid Payout (7 days after confirmed delivery) and that standard payout is 30 days after confirmed delivery.

Q16 | PARTIAL | citations_valid=True | ungrounded_numbers=[]
  reason: The customer-pays claim for change-of-mind returns matches clause 8.3, but the word 'only' is not supported: the clause lists when the seller bears freight and does not say it never does so in other cases.

**Step. Off-topic check.** Top cosine score of 3 questions that have nothing to do with the policy. If they score well below 0.68, the threshold can be set between them and the policy questions, so layer 1 blocks off-topic questions without touching any of the 20 test questions.

In [7]:
off_topic = ["What is the weather in Mumbai today?", "Who won the cricket world cup?", "How do I bake a cake?"]
for q in off_topic:
    print(round(float(index.dense_scores(q).max()), 3), "|", q)

0.426 | What is the weather in Mumbai today?
0.439 | Who won the cricket world cup?
0.424 | How do I bake a cake?

**Step. Final numbers for the report.**

In [8]:
per_q, s = rag.evaluate_retrieval(index, eval_df, ks=(1, 3, 5), mode="hybrid")
final = pd.concat([
    s.round(2).rename("value").to_frame(),
    rag.summarize_answers(results).rename("value").to_frame(),
    pd.Series({"faithfulness SUPPORTED": f"{(chk['verdict'] == 'SUPPORTED').sum()} of {len(chk)}",
               "answers with ungrounded numbers": f"{(chk['ungrounded_numbers'].str.len() > 0).sum()} of {len(chk)}"}).rename("value").to_frame(),
])
final

                                      value
any@1                                  0.81
all@1                                   0.5
any@3                                   1.0
all@3                                  0.94
any@5                                   1.0
all@5                                   1.0
MRR                                    0.91
unanswerable abstained (correct)     4 of 4
answerable wrongly abstained        1 of 16
answerable cited a correct clause  16 of 16
faithfulness SUPPORTED             14 of 15
answers with ungrounded numbers     1 of 15

**Inference**
- Retrieval (hybrid search, section title included): the top 3 holds every correct clause for 15 of 16 questions (`all@3` 0.94) and the top 5 for all 16 (`all@5` 1.00). A correct clause is ranked first for 13 of 16 (`any@1` 0.81), and `MRR` is 0.91.
- Generation: the answers in notebook 04 used the top 3 clauses of hybrid search. 15 of 16 answerable questions were answered. The one wrong refusal (Q07) is the one question that top 3 missed.
- Abstention: 4 of 4 unanswerable questions were refused.
- Faithfulness: 14 of 15 answers are SUPPORTED and 1 is PARTIAL. 1 of 15 has an ungrounded number (Q05, the computed value 2).
- Limits: the 20 questions were written from the policy with AI help, so scores may be optimistic. The judge and the answering model are the same model, which can be lenient on its own answers. The "cited a correct clause" check accepts one correct clause, not all.
- Next: re-run notebook 04 with dense search, section title and the top 5 clauses, then repeat this notebook to see if Q07 is fixed and the 4 unanswerable questions are still refused.

**Appendix. All 20 answers in full.** Every question with its retrieved clauses, citations, full answer and the expected answer.

In [9]:
exp = eval_df.set_index("qid")["expected_answer"]
for r in results:
    print(f"{r['qid']} | gold_answerable={r['gold_answerable']} | answered={r['answerable']} | "
          f"abstained_by={r['abstained_by']} | top_dense={r['top_dense']:.3f}")
    print("  retrieved:", ", ".join(r["retrieved_ids"]), "| cited:", ", ".join(r["citations"]) or "-")
    print("  Q:", r["question"])
    print("  A:", r["answer"])
    print("  Expected:", exp[r["qid"]])
    print()

Q01 | gold_answerable=1 | answered=True | abstained_by=None | top_dense=0.755
  retrieved: MOP-1.2, MOP-1.3, MOP-1.5 | cited: MOP-1.2, MOP-1.3
  Q: A seller has 96% on-time delivery and an 11% adverse review rate. Which tier is the seller in?
  A: The seller is in the Bronze tier. A seller must satisfy both thresholds for a tier (MOP-1.3). With 96% OTD, the seller meets the Gold OTD threshold (≥95%) but not the Gold ARR threshold (≤4%), since 11% exceeds 4%. Silver requires ARR ≤9%, and 11% exceeds that too. Bronze requires OTD ≥75% and ARR ≤15%, and the seller meets both (96% ≥ 75%, 11% ≤ 15%). This matches the example in MOP-1.3.
  Expected: Bronze. Both thresholds must be met, so 11% ARR rules out Gold.

Q02 | gold_answerable=1 | answered=True | abstained_by=None | top_dense=0.759
  retrieved: MOP-1.1, MOP-6.1, MOP-6.3 | cited: MOP-1.1
  Q: How many completed orders does a seller need in the 90-day window to be given a tier?
  A: A seller needs at least 15 completed orders in the trailing 90-day window to be given a tier. Sellers with fewer than 15 completed orders in that window are classified Unrated.
  Expected: At least 15. Fewer than 15 is Unrated.

Q03 | gold_answerable=1 | answered=True | abstained_by=None | top_dense=0.796
  retrieved: MOP-1.5, MOP-1.3, MOP-1.2 | cited: MOP-1.5
  Q: What commission rate does a Gold seller pay?
  A: A Gold seller pays a reduced commission rate of 11%, compared with the standard rate of 14%.
  Expected: 11% instead of the standard 14%.

Q04 | gold_answerable=1 | answered=True | abstained_by=None | top_dense=0.794
  retrieved: MOP-2.1, MOP-2.2, MOP-2.3 | cited: MOP-2.1, MOP-2.2, MOP-2.3
  Q: An order arrives 7 days after the estimated delivery date. What is the delay class and what does the seller owe?
  A: A 7-day delay falls in the Moderate class (4–10 days) under MOP-2.2. The seller is liable for the freight cost, which is charged back to the seller. Delay is measured against the estimated delivery date shown to the customer at checkout, not the carrier's estimate (MOP-2.1). Liability may be waived if the delay is due to a documented carrier failure, a declared force majeure event, or a customer address error, provided the seller raises a Liability Waiver Request within 10 calendar days of delivery (MOP-2.3). The policy clauses given do not state the freight cost amount, so the exact sum owed depends on the actual freight cost of the order.
  Expected: Moderate. Freight cost is charged back to the seller.

Q05 | gold_answerable=1 | answered=True | abstained_by=None | top_dense=0.794
  retrieved: MOP-3.2, MOP-2.4, MOP-2.2 | cited: MOP-2.4, MOP-2.2
  Q: A standard-freight order to the Northeast arrives 6 days late. How is the delay classified?
  A: The delay is classified as Minor. Under MOP-2.4, orders shipped to the Northeast get an automatic 4-day grace allowance before classification, and this order is standard freight, so the Express Freight exclusion does not apply. Working: 6 days late - 4 days grace = 2 days. Under MOP-2.2, a delay of 1–3 days is Minor.
  Expected: 4-day grace leaves 2 days, so Minor with no seller liability.

Q06 | gold_answerable=1 | answered=True | abstained_by=None | top_dense=0.795
  retrieved: MOP-2.4, MOP-2.2, MOP-8.4 | cited: MOP-2.4, MOP-2.2, MOP-8.4
  Q: An Express Freight order to the Northeast arrives 3 days late. How is it classified?
  A: The order is classified Moderate. MOP-2.4's 4-day grace allowance for North/Northeast orders does not apply to Express Freight orders, so the full 3-day delay counts. Under the MOP-2.2 thresholds alone, 3 days would be Minor (1–3 days, no seller liability). However, MOP-8.4 says Express orders delayed beyond 2 days are classified Moderate at minimum, regardless of the MOP-2.2 thresholds. Since 3 days > 2 days, the order is Moderate, meaning the freight cost is charged back to the seller.
  Expected: Moderate at minimum. The regional grace does not apply to Express.

Q07 | gold_answerable=1 | answered=False | abstained_by=llm | top_dense=0.715
  retrieved: MOP-3.2, MOP-3.1, MOP-3.4 | cited: MOP-3.2, MOP-3.1
  Q: An order worth R$ 500 is delivered 12 days late. How much platform credit does the customer get automatically?
  A: The provided clauses do not define the delay classes (Minor, Moderate, Severe, Critical), so a 12-day delay cannot be placed in a class. The credit therefore cannot be determined. MOP-3.2 gives the credit for each class. For a R$ 500 order, Minor is none, Moderate is the greater of R$ 20 or 10% (R$ 50), so R$ 50, and Severe is the greater of R$ 50 or 20% (R$ 100), so R$ 100. Critical is 100% of order value (R$ 500) plus freight, and the freight amount is not given. Under MOP-3.1 the compensation is issued as platform credit by default.
  Expected: Severe class: the greater of R$ 50 or 20% = R$ 100.

Q08 | gold_answerable=1 | answered=True | abstained_by=None | top_dense=0.684
  retrieved: MOP-3.3, MOP-3.2, MOP-3.1 | cited: MOP-3.3
  Q: Who has to approve a compensation of R$ 1,500?
  A: A compensation of R$ 1,500 is above R$ 1,000, so it requires approval from the Head of Marketplace Operations, and it must also be recorded in the Exceptions Register. It is also above R$ 300, which requires a Quality Team lead's approval. The policy lists the two approvals as separate thresholds and does not say whether the Quality Team lead's approval is still needed once the Head approves, so that point is not covered.
  Expected: Head of Marketplace Operations, and it is recorded in the Exceptions Register.

Q09 | gold_answerable=1 | answered=True | abstained_by=None | top_dense=0.833
  retrieved: MOP-4.3, MOP-3.1, MOP-4.1 | cited: MOP-3.1, MOP-4.1, MOP-4.3
  Q: When can a customer get a cash refund instead of platform credit?
  A: Compensation is normally issued as platform credit (MOP-3.1). A cash refund to the original payment method is available only if at least one of these applies: the order is classified Critical under MOP-2; the order was cancelled before carrier handoff; the customer has an open consumer protection complaint registered with Procon; or the customer account has been closed and platform credit cannot be applied (MOP-4.1). Cash refunds cannot be partial. Where a partial remedy is appropriate, platform credit must be used (MOP-4.3).
  Expected: Critical delay, cancelled before carrier handoff, open Procon complaint, or closed account.

Q10 | gold_answerable=1 | answered=True | abstained_by=None | top_dense=0.820
  retrieved: MOP-4.2, MOP-4.1, MOP-3.1 | cited: MOP-4.2, MOP-4.1, MOP-3.1
  Q: How long does a refund take if the customer paid by Pix?
  A: If a cash refund is issued to a customer who paid by Pix, it is processed within 3 business days (MOP-4.2). Cash refunds are only available in the cases listed in MOP-4.1 (for example, a Critical order, cancellation before carrier handoff, an open Procon complaint, or a closed account where platform credit cannot be applied). Otherwise, compensation is issued as platform credit by default (MOP-3.1), and the policy clauses provided do not state a processing time for platform credit.
  Expected: Within 3 business days.

Q11 | gold_answerable=1 | answered=True | abstained_by=None | top_dense=0.799
  retrieved: MOP-5.2, MOP-2.3, MOP-2.1 | cited: MOP-5.2, MOP-2.3
  Q: Can a seller get a negative review removed because the delay was caused by the carrier?
  A: No. Under MOP-5.2, a negative review may not be removed on the grounds that the cause was a carrier failure (nor because the seller disputes it or compensation was paid). However, if the delay was a documented carrier failure and seller liability was waived under MOP-2.3 (which requires a Liability Waiver Request within 10 calendar days of delivery or of the auto-cancellation date), the review is excluded from the seller's ARR calculation, though it remains visible on the listing.
  Expected: No. If liability was waived, the review is excluded from ARR but stays visible.

Q12 | gold_answerable=1 | answered=True | abstained_by=None | top_dense=0.795
  retrieved: MOP-5.4, MOP-5.2, MOP-6.3 | cited: MOP-5.4
  Q: How long does a seller have to ask for a review to be removed, and can the decision be appealed?
  A: A removal request must be raised within 30 days of the review being posted. The moderation decision is final, and there is no second-level appeal.
  Expected: 30 days. The decision is final, no second-level appeal.

Q13 | gold_answerable=1 | answered=True | abstained_by=None | top_dense=0.857
  retrieved: MOP-6.1, MOP-6.2, MOP-1.4 | cited: MOP-6.1, MOP-6.2
  Q: What happens to a seller that is still in Watch tier when the Improvement Period ends?
  A: A seller still in Watch tier at the end of the 30-day Improvement Period is subject to Listing Restriction: existing listings remain active, new listings are blocked, and category placement is deprioritised.
  Expected: Listing Restriction: new listings blocked, placement deprioritised.

Q14 | gold_answerable=1 | answered=True | abstained_by=None | top_dense=0.836
  retrieved: MOP-6.4, MOP-6.5, MOP-3.3 | cited: MOP-6.4
  Q: What must the Quality Team complete before a seller can be suspended?
  A: Before any suspension, the Quality Team must complete and record all of the following: (1) written notice to the seller with at least 10 business days to respond, except where 6.3 immediate grounds apply; (2) a review of open Liability Waiver Requests, which must be resolved first; (3) confirmation that outstanding customer orders have a fulfilment or refund plan; and (4) sign-off from a Quality Team lead.
  Expected: Written notice (10 business days), review of waiver requests, fulfilment/refund plan, lead sign-off.

Q15 | gold_answerable=1 | answered=True | abstained_by=None | top_dense=0.891
  retrieved: MOP-7.1, MOP-1.5, MOP-7.3 | cited: MOP-7.1, MOP-1.5
  Q: How many days after delivery does a Gold seller receive payout?
  A: A Gold tier seller can use Rapid Payout, which pays out 7 days after confirmed delivery. The standard payout is 30 days after confirmed delivery.
  Expected: 7 days (Rapid Payout).

Q16 | gold_answerable=1 | answered=True | abstained_by=None | top_dense=0.780
  retrieved: MOP-8.3, MOP-3.5, MOP-8.4 | cited: MOP-8.3
  Q: Who pays the freight when a customer returns an item because of a change of mind?
  A: The customer pays the freight when the return is a change of mind under the statutory withdrawal right. The seller bears freight only where the return results from a defect, a misshipment, or an item not as described.
  Expected: The customer.

Q17 | gold_answerable=0 | answered=False | abstained_by=llm | top_dense=0.722
  retrieved: MOP-6.5, MOP-6.4, MOP-7.1 | cited: -
  Q: How many days does a customer have to return an item after a change of mind?
  A: The provided clauses do not cover customer return windows or change-of-mind returns. They only cover seller suspension and reinstatement (MOP-6.4, MOP-6.5) and seller payout timing (MOP-7.1).
  Expected: Not in the policy. MOP-8.3 only mentions the statutory withdrawal right.

Q18 | gold_answerable=0 | answered=False | abstained_by=llm | top_dense=0.742
  retrieved: MOP-3.5, MOP-4.1, MOP-4.2 | cited: MOP-3.5, MOP-4.1, MOP-4.2
  Q: What refund does a customer get for a product that arrives defective?
  A: The policy does not say what refund a customer gets for a defective product. MOP-3.5 states that compensation for reasons other than delivery delay, including product defects, follows the Returns Policy and is not covered by this document. MOP-4.1 and MOP-4.2 cover when cash refunds may be issued and how fast they are processed, but they do not set out a defect-specific refund.
  Expected: Not in this policy. MOP-3.5 sends it to the Returns Policy.

Q19 | gold_answerable=0 | answered=False | abstained_by=llm | top_dense=0.691
  retrieved: MOP-1.5, MOP-7.1, MOP-7.3 | cited: MOP-1.5, MOP-7.1
  Q: What fee does a seller pay to join the Rapid Payout schedule?
  A: The policy clauses do not state any fee for joining the Rapid Payout schedule. They only say that Rapid Payout is available to Gold tier sellers (MOP-1.5, MOP-7.1), pays 7 days after confirmed delivery (MOP-7.1), and that Gold sellers pay a reduced commission of 11% versus the standard 14% (MOP-1.5). No joining fee is mentioned.
  Expected: Not in the policy. MOP-7.1 gives timing only, no fee.

Q20 | gold_answerable=0 | answered=False | abstained_by=llm | top_dense=0.714
  retrieved: MOP-4.3, MOP-4.1, MOP-4.2 | cited: -
  Q: Can a customer appeal a decision on their cash refund request?
  A: The provided clauses do not say whether a customer can appeal a decision on a cash refund request. They only cover when a cash refund may be issued (MOP-4.1), processing times (MOP-4.2), and that partial cash refunds are not supported and platform credit is used instead (MOP-4.3). They contain no appeal process.
  Expected: Not in the policy. Appeals are only mentioned for review moderation (MOP-5.4).